package com.joaopedro.mock_api_caseveiculos.repository;

import com.joaopedro.mock_api_caseveiculos.domain.*;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class VeiculoData {
    private final List<VeiculoMock> veiculosMocks = new ArrayList<>(5);

    //Inicializando em Memória dados sobre dos veículos
    {
        VeiculoMock veiculo1 = VeiculoMock.builder()
                .codigo("000")
                .mensagem("Sucesso")
                .placa("FUD5J98")
                .chassi("3N1BB7ADXHY200644")
                .ufJurisdicao("SP")
                .nomeMunicipioEmplacamento("VALINHOS")
                .anoFabricacao(2016)
                .anoModelo(2017)
                .marca("I")
                .modelo("NISSAN SENTRA 20SV CVT")
                .tipoVeiculo("Automovel")
                .tipoCarroceria("NAO APLICAVEL")
                .numeroCarroceria("")
                .corPredominante("Cinza")
                .combustivel("ALCOOL/GASOLINA")
                .potencia(140)
                .cilindradas(1997)
                .capacidadePassageiros(5)
                .numeroCaixaCambio("")
                .numeroEixos(2)
                .numeroMotor("MR20980798H")
                .dataEmplacamento("09092016")
                .quantidadeAquisicoes(8)
                .dataUltimaAquisicao(null)
                .ufUltimaAquisicao("SP")
                .ufAtual("SP")
                .nomeMunicipioUltimaAquisicao("MOGI DAS CRUZES")
                .indicadoresFipe(List.of(
                        FipeIndicadorMock.builder()
                                .codigoFIPE("023123-1")
                                .valores(List.of(
                                        FipeValueMock.builder()
                                                .valorFIPE(67727.0)
                                                .dataConsulta("02/2025")
                                                .nomenclaturaFIPE("Nissan-Sentra SV 2.0 FlexStart 16V Aut.")
                                                .indiceComparacao(2.04)
                                                .desvalorizacao(false)
                                                .build(),
                                        FipeValueMock.builder()
                                                .valorFIPE(66373.0)
                                                .dataConsulta("01/2025")
                                                .nomenclaturaFIPE("Nissan-Sentra SV 2.0 FlexStart 16V Aut.")
                                                .indiceComparacao(3.50)
                                                .desvalorizacao(false)
                                                .build(),
                                        FipeValueMock.builder()
                                                .valorFIPE(64129.0)
                                                .dataConsulta("12/2024")
                                                .nomenclaturaFIPE("Nissan-Sentra SV 2.0 FlexStart 16V Aut.")
                                                .indiceComparacao(3.00)
                                                .desvalorizacao(true)
                                                .build()
                                ))
                                .build()
                ))
                .indicadoresMolicar(List.of(
                        MolicarIndicadorMock.builder()
                                .codigo("03701339-7")
                                .descricao("NISSAN SENTRA SV N.GERACAO 2.0 16V CVT FLEXSTART 4P Eta./Gas.")
                                .build()
                ))
                .indicadoresIcarros(List.of(
                        IcarrosIndicadorMock.builder()
                                .codigoICARROS("26099")
                                .valorICARROS(64798.66)
                                .mesConsulta("01/2025")
                                .nomenclaturaICARROS("Sentra SV 2.0 16V CVT (Flex)")
                                .indiceComparacao(2.80)
                                .desvalorizacao(false)
                                .build(),
                        IcarrosIndicadorMock.builder()
                                .codigoICARROS("26099")
                                .valorICARROS(63033.42)
                                .mesConsulta("12/2024")
                                .nomenclaturaICARROS("Sentra SV 2.0 16V CVT (Flex)")
                                .indiceComparacao(1.86)
                                .desvalorizacao(true)
                                .build(),
                        IcarrosIndicadorMock.builder()
                                .codigoICARROS("26099")
                                .valorICARROS(64228.30)
                                .mesConsulta("11/2024")
                                .nomenclaturaICARROS("Sentra SV 2.0 16V CVT (Flex)")
                                .indiceComparacao(3.99)
                                .desvalorizacao(true)
                                .build()
                ))
                .build();
        VeiculoMock veiculo2 = VeiculoMock.builder()
                .codigo("001")
                .mensagem("Sucesso")
                .placa("ABC1D23")
                .chassi("9BWZZZ377VT004251")
                .ufJurisdicao("RJ")
                .nomeMunicipioEmplacamento("RIO DE JANEIRO")
                .anoFabricacao(2018)
                .anoModelo(2019)
                .marca("V")
                .modelo("VOLKSWAGEN GOL 1.0 MPI")
                .tipoVeiculo("Automovel")
                .tipoCarroceria("NAO APLICAVEL")
                .numeroCarroceria("")
                .corPredominante("Branco")
                .combustivel("GASOLINA")
                .potencia(76)
                .cilindradas(999)
                .capacidadePassageiros(5)
                .numeroCaixaCambio("")
                .numeroEixos(2)
                .numeroMotor("CHT123456789")
                .dataEmplacamento("15052018")
                .quantidadeAquisicoes(5)
                .dataUltimaAquisicao("10012023")
                .ufUltimaAquisicao("RJ")
                .ufAtual("RJ")
                .nomeMunicipioUltimaAquisicao("NITEROI")
                .indicadoresFipe(List.of(
                        FipeIndicadorMock.builder()
                                .codigoFIPE("001234-5")
                                .valores(List.of(
                                        FipeValueMock.builder()
                                                .valorFIPE(45000.0)
                                                .dataConsulta("02/2025")
                                                .nomenclaturaFIPE("Volkswagen-Gol 1.0 MPI 8V Flex 4p")
                                                .indiceComparacao(1.50)
                                                .desvalorizacao(false)
                                                .build(),
                                        FipeValueMock.builder()
                                                .valorFIPE(44000.0)
                                                .dataConsulta("01/2025")
                                                .nomenclaturaFIPE("Volkswagen-Gol 1.0 MPI 8V Flex 4p")
                                                .indiceComparacao(1.20)
                                                .desvalorizacao(true)
                                                .build(),
                                        FipeValueMock.builder()
                                                .valorFIPE(43000.0)
                                                .dataConsulta("12/2024")
                                                .nomenclaturaFIPE("Volkswagen-Gol 1.0 MPI 8V Flex 4p")
                                                .indiceComparacao(1.00)
                                                .desvalorizacao(true)
                                                .build()
                                ))
                                .build()
                ))
                .indicadoresMolicar(List.of(
                        MolicarIndicadorMock.builder()
                                .codigo("04567890-1")
                                .descricao("VOLKSWAGEN GOL 1.0 MPI 8V FLEX 4P")
                                .build()
                ))
                .indicadoresIcarros(List.of(
                        IcarrosIndicadorMock.builder()
                                .codigoICARROS("12345")
                                .valorICARROS(43500.0)
                                .mesConsulta("01/2025")
                                .nomenclaturaICARROS("Gol 1.0 MPI 8V Flex 4p")
                                .indiceComparacao(1.30)
                                .desvalorizacao(false)
                                .build(),
                        IcarrosIndicadorMock.builder()
                                .codigoICARROS("12345")
                                .valorICARROS(42500.0)
                                .mesConsulta("12/2024")
                                .nomenclaturaICARROS("Gol 1.0 MPI 8V Flex 4p")
                                .indiceComparacao(1.10)
                                .desvalorizacao(true)
                                .build(),
                        IcarrosIndicadorMock.builder()
                                .codigoICARROS("12345")
                                .valorICARROS(43000.0)
                                .mesConsulta("11/2024")
                                .nomenclaturaICARROS("Gol 1.0 MPI 8V Flex 4p")
                                .indiceComparacao(1.40)
                                .desvalorizacao(true)
                                .build()
                ))
                .build();
        VeiculoMock veiculo3 = VeiculoMock.builder()
                .codigo("002")
                .mensagem("Sucesso")
                .placa("XYZ9W87")
                .chassi("9BABCD12345678901")
                .ufJurisdicao("MG")
                .nomeMunicipioEmplacamento("BELO HORIZONTE")
                .anoFabricacao(2020)
                .anoModelo(2021)
                .marca("F")
                .modelo("FIAT ARGO DRIVE 1.3")
                .tipoVeiculo("Automovel")
                .tipoCarroceria("NAO APLICAVEL")
                .numeroCarroceria("")
                .corPredominante("Vermelho")
                .combustivel("FLEX")
                .potencia(109)
                .cilindradas(1332)
                .capacidadePassageiros(5)
                .numeroCaixaCambio("")
                .numeroEixos(2)
                .numeroMotor("FIA987654321")
                .dataEmplacamento("20032020")
                .quantidadeAquisicoes(3)
                .dataUltimaAquisicao("05082022")
                .ufUltimaAquisicao("MG")
                .ufAtual("MG")
                .nomeMunicipioUltimaAquisicao("CONTAGEM")
                .indicadoresFipe(List.of(
                        FipeIndicadorMock.builder()
                                .codigoFIPE("002345-6")
                                .valores(List.of(
                                        FipeValueMock.builder()
                                                .valorFIPE(65000.0)
                                                .dataConsulta("02/2025")
                                                .nomenclaturaFIPE("Fiat-Argo Drive 1.3 Flex 8V 4p")
                                                .indiceComparacao(2.00)
                                                .desvalorizacao(false)
                                                .build(),
                                        FipeValueMock.builder()
                                                .valorFIPE(64000.0)
                                                .dataConsulta("01/2025")
                                                .nomenclaturaFIPE("Fiat-Argo Drive 1.3 Flex 8V 4p")
                                                .indiceComparacao(1.80)
                                                .desvalorizacao(true)
                                                .build(),
                                        FipeValueMock.builder()
                                                .valorFIPE(63000.0)
                                                .dataConsulta("12/2024")
                                                .nomenclaturaFIPE("Fiat-Argo Drive 1.3 Flex 8V 4p")
                                                .indiceComparacao(1.60)
                                                .desvalorizacao(true)
                                                .build()
                                ))
                                .build()
                ))
                .indicadoresMolicar(List.of(
                        MolicarIndicadorMock.builder()
                                .codigo("05678901-2")
                                .descricao("FIAT ARGO DRIVE 1.3 FLEX 8V 4P")
                                .build()
                ))
                .indicadoresIcarros(List.of(
                        IcarrosIndicadorMock.builder()
                                .codigoICARROS("67890")
                                .valorICARROS(64500.0)
                                .mesConsulta("01/2025")
                                .nomenclaturaICARROS("Argo Drive 1.3 Flex 8V 4p")
                                .indiceComparacao(1.90)
                                .desvalorizacao(false)
                                .build(),
                        IcarrosIndicadorMock.builder()
                                .codigoICARROS("67890")
                                .valorICARROS(63500.0)
                                .mesConsulta("12/2024")
                                .nomenclaturaICARROS("Argo Drive 1.3 Flex 8V 4p")
                                .indiceComparacao(1.70)
                                .desvalorizacao(true)
                                .build(),
                        IcarrosIndicadorMock.builder()
                                .codigoICARROS("67890")
                                .valorICARROS(64000.0)
                                .mesConsulta("11/2024")
                                .nomenclaturaICARROS("Argo Drive 1.3 Flex 8V 4p")
                                .indiceComparacao(1.80)
                                .desvalorizacao(true)
                                .build()
                ))
                .build();

        veiculosMocks.addAll(List.of(veiculo1,veiculo2,veiculo3));
    }

    public List<VeiculoMock> getVeiculosMocks() {
        return veiculosMocks;
    }
}